minio:
  endpoint: http://192.168.10.8:9200
  access-key: <access-key>
  secret-key: <secret-key>
  bucket-name: <bucket-name>

aliyun:
  sms:
    access-key-id: <access-key-id>
    access-key-secret: <access-key-secret>
    endpoint: dysmsapi.aliyuncs.com